package view;

import dao.FlightDAO;
import java.io.File;
import model.Flight;
import util.Database;
import util.ReportGenerator;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.util.List;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FlightManagementFrame extends javax.swing.JFrame {
    private FlightDAO flightDao;
    private ReportGenerator reportGenerator;
    private DefaultTableModel flightTableModel;
    public FlightManagementFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setupDatabase();
        initializeTable();
        loadFlights();

        btnSave.addActionListener(e -> saveFlight());
        btnUpdate.addActionListener(e -> updateFlight());
        btnDelete.addActionListener(e -> deleteFlight());
        btnReport.addActionListener(e -> generateFlightReport());
        btnTicketForm.addActionListener(e -> {
            new TicketManagementFrame().setVisible(true);
            dispose();
        });
        btnTransactionForm.addActionListener(e -> {
            new TransactionManagementFrame().setVisible(true);
            dispose();
        });
        
        this.reportGenerator = new ReportGenerator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFlightCode = new javax.swing.JTextField();
        txtFlightName = new javax.swing.JTextField();
        txtDeparture = new javax.swing.JTextField();
        txtArrival = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTicketForm = new javax.swing.JButton();
        btnTransactionForm = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Penerbangan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Penerbangan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Maskapai");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kota Asal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kota Tujuan");

        txtFlightCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFlightName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDeparture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtArrival.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Penerbangan", "Nama Maskapai", "Kota Asal", "Kota Tujuan"
            }
        ));
        jScrollPane1.setViewportView(flightTable);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Tambah");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Ubah");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Hapus");

        btnTicketForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTicketForm.setText("Form Tiket");

        btnTransactionForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransactionForm.setText("Form Transaksi");

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport.setText("Laporan");

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Form Penerbangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFlightCode, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtFlightName)
                            .addComponent(txtDeparture)
                            .addComponent(txtArrival))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTicketForm, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTransactionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFlightCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTicketForm)
                    .addComponent(btnTransactionForm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupDatabase() {
        try {
            Connection connection = Database.getConnection();
            flightDao = new FlightDAO(connection);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Connection Failed: " + e.getMessage());
        }
    }

    private void initializeTable() {
        flightTableModel = new DefaultTableModel(new String[]{"Kode Penerbangan", "Nama Maskapai", "Kota Asal", "Kota Tujuan"}, 0);
        flightTable.setModel(flightTableModel);
        for (int column = 0; column < flightTable.getColumnCount(); column++) {
            int headerWidth = flightTable.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(flightTable, flightTable.getColumnName(column), false, false, 0, column)
                    .getPreferredSize().width;
            flightTable.getColumnModel().getColumn(column).setPreferredWidth(headerWidth);
        }       
        flightTable.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = flightTable.getSelectedRow();
            if (selectedRow != -1) {
                String flightCode = flightTable.getValueAt(selectedRow, 0).toString();
                String flightName = flightTable.getValueAt(selectedRow, 1).toString();
                String departure = flightTable.getValueAt(selectedRow, 2).toString();
                String arrival = flightTable.getValueAt(selectedRow, 3).toString();

                txtFlightCode.setText(flightCode);
                txtFlightName.setText(flightName);
                txtDeparture.setText(departure);
                txtArrival.setText(arrival);
            }
        });
    }

    private void loadFlights() {
        try {
            List<Flight> flights = flightDao.getAllFlights();
            flightTableModel.setRowCount(0);
            for (Flight flight : flights) {
                flightTableModel.addRow(new Object[]{flight.getFlightCode(), flight.getFlightName(), flight.getDeparture(), flight.getArrival()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data penerbangan: " + e.getMessage());
        }
    }

    private void saveFlight() {
        try {
            if (txtFlightCode.getText().isEmpty() || 
                txtFlightName.getText().isEmpty() || 
                txtDeparture.getText().isEmpty() || 
                txtArrival.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "Semua data harus terisi sebelum menambah penerbangan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Flight flight = new Flight(
                txtFlightCode.getText(),
                txtFlightName.getText(),
                txtDeparture.getText(),
                txtArrival.getText()
            );
            flightDao.addFlight(flight);
            loadFlights();
            JOptionPane.showMessageDialog(this, "Penerbangan berhasil ditambahkan!");
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan penerbangan: " + e.getMessage());
        }
    }

    private void updateFlight() {
        int selectedRow = flightTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih penerbangan yang ingin diperbarui!");
            return;
        }
        try {
            Flight flight = new Flight(
                txtFlightCode.getText(),
                txtFlightName.getText(),
                txtDeparture.getText(),
                txtArrival.getText()
            );
            flightDao.updateFlight(flight);
            loadFlights();
            JOptionPane.showMessageDialog(this, "Penerbangan berhasil diperbarui!");
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui penerbangan: " + e.getMessage());
        }
    }

    private void deleteFlight() {
        int selectedRow = flightTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih penerbangan yang ingin dihapus!");
            return;
        }
        try {
            String flightCode = flightTableModel.getValueAt(selectedRow, 0).toString();
            flightDao.deleteFlight(flightCode);
            loadFlights();
            JOptionPane.showMessageDialog(this, "Penerbangan berhasil dihapus!");
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus penerbangan: " + e.getMessage());
        }
    }
    
    private void generateFlightReport() {
        if (flightTableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada penerbangan untuk disimpan ke laporan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Lokasi untuk Menyimpan Laporan Penerbangan");
        
        fileChooser.setFileFilter(new FileNameExtensionFilter("CSV Files", "csv"));
        fileChooser.setSelectedFile(new File("laporan_penerbangan"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try {
                if (!fileToSave.getName().endsWith(".csv")) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
                }
                reportGenerator.generateFlightReport(fileToSave.getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Laporan Penerbangan berhasil disimpan!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan laporan: " + e.getMessage());
            }
        }
    }
    
    private void clearForm() {
        txtFlightCode.setText("");
        txtFlightName.setText("");
        txtDeparture.setText("");
        txtArrival.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTicketForm;
    private javax.swing.JButton btnTransactionForm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable flightTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtFlightCode;
    private javax.swing.JTextField txtFlightName;
    // End of variables declaration//GEN-END:variables
}
